import numpy as np
import streamlit as st

from src.config import CURRENCY, NAMED_SCENARIOS, OPTIMIZED_LIMITS, ORIGINAL_LIMITS
from src.data_loader import load_precomputed_scenarios
from src.optimization import (
    fallback_balanced_dataframe,
    get_scenario_for_lambda,
    scenario_to_dataframe,
)
from src.visualizations import delta_pct_bar, delta_waterfall, limits_comparison_bar

from pathlib import Path as _Path
_ASSETS = _Path(__file__).parent.parent / "assets"
st.set_page_config(page_title="KinetiX · Scenario Runner", page_icon=str(_ASSETS / "favicon.png"), layout="wide")

# inject CSS
_css = _ASSETS / "style.css"
if _css.exists():
    st.markdown(f"<style>{_css.read_text()}</style>", unsafe_allow_html=True)
st.title("⚙️ Optimisation Scenario Runner")
st.caption("Explore how different risk-aversion levels change the recommended limits.")
st.divider()

scenarios = load_precomputed_scenarios()

# ── data source banner ─────────────────────────────────────────────────────────
if scenarios is not None:
    st.success(
        "✅  **Live precomputed results loaded.** "
        "Scenarios were generated by running the Gurobi solver across multiple λ values."
    )
else:
    st.warning(
        "⚠️  **Precomputed scenarios not found.** "
        "Showing the Balanced scenario (λ = 0.01) from the committed optimisation output. "
        "Run `python precompute_scenarios.py` once to enable full scenario exploration."
    )

st.divider()

# ── scenario controls ──────────────────────────────────────────────────────────
col_ctrl, col_desc = st.columns([2, 3])

with col_ctrl:
    st.subheader("Controls")

    preset = st.radio(
        "Scenario preset",
        options=["Cost-Focused", "Balanced", "Stability-Focused", "Custom"],
        index=1,
        help="Presets map to common actuarial objectives.",
    )

    if preset == "Custom":
        lambda_log = st.slider(
            "λ (log scale)", min_value=-7.0, max_value=0.0, value=-2.0, step=0.5,
            help="λ controls the trade-off between expected cost (low λ) and variance (high λ).",
        )
        lambda_val = 10 ** lambda_log
    else:
        lambda_val = NAMED_SCENARIOS[preset]["lambda"]
        st.markdown(f"**λ = {lambda_val:.0e}**")

    max_adj_pct = st.slider(
        "Max adjustment bound (%)", min_value=1, max_value=10, value=5,
        help="Maximum % change allowed for any single service limit.",
    )

with col_desc:
    st.subheader("What this scenario means")
    if preset != "Custom":
        st.info(NAMED_SCENARIOS[preset]["description"])

    col_d1, col_d2, col_d3 = st.columns(3)
    col_d1.metric("λ value",   f"{lambda_val:.2e}")
    col_d2.metric("Max adj.",  f"±{max_adj_pct}%")
    col_d3.metric("Budget",    "Neutral (Σδ = 0)")

    from src.components import info_block
    info_block("What does λ do?",
        "<strong>λ (lambda)</strong> is the risk-aversion parameter that controls the trade-off "
        "between two competing objectives:<br><br>"
        "<strong>Low λ</strong> (≤ 1e-5) → Cost minimisation. Reduce expected payout; accept more variance.<br>"
        "<strong>Medium λ</strong> (~1e-2) → Balanced. Reduce both cost and variance.<br>"
        "<strong>High λ</strong> (≥ 0.1) → Stability. Minimise variance; accept slightly higher cost.<br><br>"
        "Higher λ means the model is more risk-averse — it prefers stable, predictable payouts "
        "even if the average is slightly higher."
    )

st.divider()

# ── load or fallback result ────────────────────────────────────────────────────
if scenarios is not None and preset != "Custom":
    scenario_data = get_scenario_for_lambda(scenarios, lambda_val)
    if scenario_data:
        df_scenario = scenario_to_dataframe(scenario_data)
    else:
        df_scenario = fallback_balanced_dataframe()
elif scenarios is not None and preset == "Custom":
    scenario_data = get_scenario_for_lambda(scenarios, lambda_val)
    df_scenario   = scenario_to_dataframe(scenario_data) if scenario_data else fallback_balanced_dataframe()
else:
    scenario_data = None
    df_scenario = fallback_balanced_dataframe()

# Apply max_adj_pct clamp for display (informational — actual solver respects adaptive ε)
if max_adj_pct != 5:
    factor = max_adj_pct / 5.0
    df_scenario = df_scenario.copy()
    df_scenario["delta"]         = df_scenario["delta"] * factor
    df_scenario["adjusted_limit"]= df_scenario["original_limit"] + df_scenario["delta"]
    df_scenario["delta_pct"]     = df_scenario["delta"] / df_scenario["original_limit"] * 100
    st.caption(
        f"Note: Adjustments rescaled to ±{max_adj_pct}% bound. "
        "This is an approximation; run precompute_scenarios.py with updated bounds for exact results."
    )

# ── results ────────────────────────────────────────────────────────────────────
st.subheader("Scenario Results")

# Compute expected reimbursement saving for this scenario
if scenario_data and "expected_payout_total" in (scenario_data or {}):
    # Compare this scenario's expected payout against the pure-original baseline
    # (the lambda_sweep entry with the lowest lambda ≈ no variance penalty ≈ original behaviour)
    sweep = scenarios.get("lambda_sweep", []) if scenarios else []
    baseline = max((s["expected_payout_total"] for s in sweep), default=scenario_data["expected_payout_total"])
    exp_saving = baseline - scenario_data["expected_payout_total"]
    exp_payout = scenario_data["expected_payout_total"]
    exp_variance = scenario_data.get("variance_total", None)
else:
    exp_saving = None
    exp_payout = None
    exp_variance = None

col_k1, col_k2, col_k3, col_k4 = st.columns(4)
col_k1.metric("λ", f"{lambda_val:.2e}")
col_k2.metric("Limits ↑", int((df_scenario["delta"] > 0).sum()))
col_k3.metric("Limits ↓", int((df_scenario["delta"] < 0).sum()))
if exp_payout is not None:
    col_k4.metric("Exp. Reimb.",
                  f"{exp_payout/1e6:.3f}M",
                  delta=f"{exp_saving/1e3:.0f}K saved" if exp_saving and exp_saving > 0 else "neutral")
else:
    col_k4.metric("Budget", "Neutral ✓")

tab_charts, tab_table = st.tabs(["📈 Charts", "📋 Table"])

with tab_charts:
    col1, col2 = st.columns(2)
    with col1:
        st.plotly_chart(limits_comparison_bar(df_scenario), use_container_width=True)
    with col2:
        st.plotly_chart(delta_waterfall(df_scenario), use_container_width=True)
    st.plotly_chart(delta_pct_bar(df_scenario), use_container_width=True)

with tab_table:
    st.dataframe(
        df_scenario.rename(columns={
            "service_id":      "ID",
            "service_name":    "Service",
            "original_limit":  f"Original ({CURRENCY})",
            "adjusted_limit":  f"Adjusted ({CURRENCY})",
            "delta":           f"Δ ({CURRENCY})",
            "delta_pct":       "Δ%",
        }).style.format({
            f"Original ({CURRENCY})": "{:,.0f}",
            f"Adjusted ({CURRENCY})": "{:,.0f}",
            f"Δ ({CURRENCY})":        "{:+,.0f}",
            "Δ%":                     "{:+.2f}%",
        }),
        use_container_width=True,
        hide_index=True,
    )
